resources:
  repositories:
  - repository: cv
    type: github
    endpoint: twistsmyth
    name: twistsmyth/cv
  - repository: space-invaders
    type: github
    endpoint: twistsmyth
    name: twistsmyth/space-invaders


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: space-invaders

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # scripted
      echo 'merge site'
      mv $(build.sourcesDirectory)/space-invaders/index.html $(build.sourcesDirectory)/space-invaders/space.html
      cp -r $(build.sourcesDirectory)/space-invaders/. $(build.sourcesDirectory)/cv/. $(build.sourcesDirectory)
      az artifacts universal publish --organization https://twistsmyth.visualstudio.com/ --feed twistsmyth --name cvw --version 0.0.2 --description "website" --path $(Build.ArtifactStagingDirectory)


