resources:
  repositories:
  - repository: cv
    type: github
    endpoint: twistsmyth
    name: twistsmyth/cv
  - repository: space-invaders
    type: github
    endpoint: twistsmyth
    name: twistsmyth/space-invaders


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: space-invaders

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # scripted
      echo 'merge site'
      mv $(build.sourcesDirectory)/space-invaders/index.html $(build.sourcesDirectory)/space-invaders/space.html
      cp -r $(build.sourcesDirectory)/space-invaders/. $(build.sourcesDirectory)/cv/. $(Build.ArtifactStagingDirectory)

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)/'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '1f99d44f-ae24-4ec7-b6dc-5d544f9d8d16'
    vstsFeedPackagePublish: 'cvw'
    versionOption: 'custom'
    versionPublish: '0.0.1'
    packagePublishDescription: 'Website'


