resources:
  repositories:
  - repository: cv
    type: github
    endpoint: twistsmyth
    name: twistsmyth/cv
  - repository: space-invaders
    type: github
    endpoint: twistsmyth
    name: twistsmyth/space-invaders


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # scripted
      echo 'merge site'
      mv $(build.sourcesDirectory)/space-invaders/index.html $(build.sourcesDirectory)/space-invaders/space.html
      mv $(build.sourcesDirectory)/space-invaders/. $(build.sourcesDirectory)/cv


- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(build.sourcesDirectory)/cv'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '1f99d44f-ae24-4ec7-b6dc-5d544f9d8d16'
    vstsFeedPackagePublish: 'cv'
    versionOption: 'custom'
    versionPublish: '0.0.1'
    publishedPackageVar: 'cv'

